name: YBTO 8th
title: YBTO 8th| YBTO 8th Official
description: YBTO 8th Official
  we are the best
tags:
  - technology
  - company
  - Tianjin No.1 High School
  - website
  - development
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
