name: Star Ring Corporation
title: SRC | Star Ring Corporation Official
description: Star Ring Corporation Official
  May the force be with you
tags:
  - website
  - official
  - technology
  - development
  - starring
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
